Feat/#127
Yapp-17th/Web_2_Client pull request #130
Opened 2020-12-25 12:02 UTC by Lavegaa

혼자연습하기 녹화영상 재생
hls.js를 활용한 영상 재생
todo
아이콘 수정

2020-12-25 12:32 UTC, dididy requested changes
사용하지 않는 주석이랑 라이브러리만 정리하면 될 것 같네요

수고 정말 많으셨어요!!

2020-12-25 12:32 UTC, dididy commented on package.json
> +    "videojs-contrib-hls": "^5.15.0"
이 두개 지금도 사용하고있나요?

2020-12-25 12:32 UTC, dididy commented on public/index.html
> +
해당 주석도 사용하지 않는다면 삭제하면 좋을 것 같습니다

2020-12-25 12:32 UTC, dididy commented on src/pages/MyVideoPage/MyVideoPage.js
> +    });
실제 동작 하지 않는 경우는 삭제에 대한 부분인가요?

2020-12-25 12:32 UTC, dididy commented on src/pages/MyVideoPage/MyVideoPage.js
> +      </Paper>
이부분이 material-ui를 사용한 부분이군요 참고하겠습니다!

2020-12-25 12:32 UTC, dididy commented on src/pages/VideoPage/VideoPage.js
> +          xhr.withCredentials = true;
이게 재생을 제대로 하지 못하게 하는 문제의 근원이었군요..

2020-12-25 12:32 UTC, dididy commented on src/pages/VideoPage/VideoPage.js
> +    }
hls 쌩으로 쓰는 경우엔 이렇게 하는군요 배워갑니다

2020-12-25 12:32 UTC, dididy commented on src/pages/VideoPage/VideoPage.js
> +            <source src={uploadedLocation} type="video/m3u8" />
source태그의 type attribute로 형식을 지정할 수 있군요

2020-12-25 12:35 UTC, Lavegaa commented on src/pages/MyVideoPage/MyVideoPage.js
> +    });
네네 savedLocation가 null인경우와 url에 videos가 없는 경우에는 영상이 정상 작동하지 않아서 filter로 걸러냈습니다.

2020-12-25 12:36 UTC, Lavegaa commented on src/pages/VideoPage/VideoPage.js
> +          xhr.withCredentials = true;
네네 재호님이 해결해주셨어요

2020-12-25 12:36 UTC, Lavegaa commented on src/pages/VideoPage/VideoPage.js
> +            <source src={uploadedLocation} type="video/m3u8" />
음 해당부분 빼고 돌리는건 아직 테스트 안해봤네요ㅋㅋㅋ아까 소리가 안나서 테스트하던 코드 중 하나였어요!
사용 안하는 코드 수정하고 다시 올릴게요

2020-12-25 12:37 UTC, Lavegaa commented on package.json
> +    "videojs-contrib-hls": "^5.15.0"
사용안합니다! 삭제하겠습니다!

2020-12-25 14:04 UTC, dididy approved these changes

2020-12-25 14:06 UTC, merged

2020-12-28 15:22 UTC, dididy commented
# resolve #78

2020-12-28 15:26 UTC, dididy commented
> resolve #127